name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Deploy to oss.sonatype.org
        env:
          USERNAME: ${{ secrets.OSS_SONATYPE_ORG_USERNAME }}
          PASSWORD: ${{ secrets.OSS_SONATYPE_ORG_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo -e "${GPG_PRIVATE_KEY}" | gpg --import

          GITHUB_TAG=${GITHUB_REF#refs/tags/}
          GITHUB_VERSION=${GITHUB_TAG#"v"}

          mkdir -p ~/.m2
          cp -a ./settings.maven.xml ~/.m2/settings.xml

          mvn -B versions:set -DnewVersion=${GITHUB_VERSION}
          mvn package javadoc:jar source:jar gpg:sign deploy
