name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Deploy to Github Package Registry
        env:
          USERNAME: ${{ secrets.OSS_SONATYPE_ORG_USERNAME }}
          PASSWORD: ${{ secrets.OSS_SONATYPE_ORG_PASSWORD }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>sonatype-nexus-staging</id><username>${USERNAME}</username><password>${PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml

          GITHUB_TAG=${GITHUB_REF#refs/tags/}
          GITHUB_VERSION=${GITHUB_TAG#"v"}

          mvn -B versions:set -DnewVersion=${GITHUB_VERSION}
          mvn javadoc:jar source:jar deploy
